[build-system]
requires = [
    "setuptools>=42",
    "termcolor",
    "tabulate",
    "pytest",
    "colorama",
    "psutil",
    "customtkinter",
    "opencv-python",
    "numpy",
    "pyautogui",
    "pynput",
    "wheel"
]
build-backend = "setuptools.build_meta"